version: 2
updates:
    # Adding new check for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    # Optional: specify reviewers to automatically request review on Dependabot PRs
    # reviewers:
    #   - "openedx/xxx"
